# Generated by Django 2.0.7 on 2018-09-21 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_sector', models.CharField(max_length=254)),
                ('business_activity', models.CharField(max_length=254)),
                ('permit_number', models.CharField(max_length=30)),
                ('paid_permit', models.CharField(max_length=30)),
                ('permit_bal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.BigIntegerField()),
                ('floor_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Footprints',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('osm_id', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('plot_no', models.FloatField()),
                ('height', models.FloatField()),
                ('category', models.CharField(max_length=254)),
                ('fid', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.IntegerField()),
                ('parcel_id', models.IntegerField()),
                ('parcelid', models.IntegerField()),
                ('status', models.CharField(max_length=22)),
                ('zone_no', models.CharField(max_length=50)),
                ('plot_no', models.CharField(max_length=50)),
                ('ref_plot_n', models.CharField(max_length=50)),
                ('sq_km', models.FloatField()),
                ('area', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.FloatField()),
                ('amount_pai', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Parking',
            },
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
                ('phone_no', models.CharField(max_length=10)),
                ('footprints', models.ForeignKey(db_column='footprints', on_delete=django.db.models.deletion.CASCADE, to='ebiz.Footprints')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('room_area', models.FloatField()),
                ('floor', models.ForeignKey(db_column='floor', on_delete=django.db.models.deletion.CASCADE, to='ebiz.Floors')),
            ],
        ),
        migrations.AddField(
            model_name='floors',
            name='footprint',
            field=models.ForeignKey(db_column='footprint', on_delete=django.db.models.deletion.CASCADE, to='ebiz.Footprints'),
        ),
        migrations.AddField(
            model_name='business_info',
            name='room',
            field=models.ForeignKey(db_column='room', on_delete=django.db.models.deletion.CASCADE, to='ebiz.Rooms'),
        ),
    ]
