# Generated by Django 2.0.7 on 2018-10-06 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=200)),
                ('idno', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_operators',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='business_info',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='business_info',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='business_info',
            table='business_information',
        ),
        migrations.AddField(
            model_name='businessoperator',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebiz.Business_Info'),
        ),
    ]
