# Generated by Django 2.0.7 on 2018-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebiz', '0002_auto_20181006_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
