# Generated by Django 2.0.7 on 2018-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebiz', '0003_auto_20181006_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='perit_expected',
            field=models.CharField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
