# Generated by Django 2.0.7 on 2018-10-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebiz', '0004_business_info_perit_expected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_info',
            old_name='perit_expected',
            new_name='permit_expected',
        ),
        migrations.RemoveField(
            model_name='business_info',
            name='permit_bal',
        ),
    ]
